const log = {
    "2020-09-02": [
        "Avo",
        "Cab",
        "Car",
        "Cuc",
        "Gar",
        "GrB",
        "Lee",
        "Oni",
        "Tom",
    ],
    "2020-09-03": ["Cab", "Gar", "GrB", "Oni", "Tom"],
    "2020-09-04": ["Bea", "Cab", "Cuc", "Gar", "Oni", "Tom", "SpO"],
    "2020-09-05": ["Bea", "Cab", "Car", "Gar", "Oni", "Pea", "Tom"],
    "2020-09-06": [
        "Bea",
        "Cab",
        "Car",
        "Gar",
        "Grb",
        "Mus",
        "Oni",
        "Pot",
        "Tom",
    ],
    "2020-09-07": ["Bea", "Cab", "Car", "Cou", "Gar", "Oni", "Pea", "Tom"],
    "2020-09-08": ["Cab", "Car", "Gar", "Oni", "Tom"],
    "2020-09-09": ["Cuc", "GrB", "Mus", "Oni", "Pep", "Tom"],
    "2020-09-10": ["Let", "Pot"],
    "2020-09-11": ["Car", "Cuc", "GrB", "Let", "Tom"],
    "2020-09-12": ["Car", "Cor", "Gar", "GrB", "Let", "Mus"],
    "2020-09-13": ["Avo", "Car", "Cuc", "Gar", "GrB", "Let", "Pot", "Squ"],
    "2020-09-14": ["GrB", "Pot", "Squ", "Cel", "Mus", "Oli", "Let", "Lee"],
    "2020-09-15": ["Pot", "Car", "GrB", "Oni", "Squ", "Cor"],
    "2020-09-16": [
        "Bea",
        "Car",
        "Cel",
        "Cou",
        "Gar",
        "Pep",
        "Cuc",
        "Let",
        "Tom",
        "Oli",
    ],
    "2020-09-17": ["Bea", "Cuc", "Oni", "Tom", "Pot", "Cha"],
    "2020-09-18": ["Pot", "Lee", "Cou", "Cel", "Cha"],
    "2020-09-19": [
        "Pot",
        "Lee",
        "Cou",
        "Cel",
        "Tom",
        "Let",
        "Bea",
        "Oli",
        "Car",
        "Cuc",
    ],
    "2020-09-20": ["Cuc", "Oli", "Car", "Bea", "Let", "Avo", "Tom"],
    "2020-09-21": ["Oni", "Car", "Pot", "Squ", "Let", "Oli", "Avo", "Tom"],
    "2020-09-22": [
        "Oni",
        "Car",
        "Pot",
        "Squ",
        "Cou",
        "Gar",
        "Tom",
        "Mus",
        "Let",
        "Oli",
    ],
    "2020-09-23": ["Tom", "Car", "Cou", "Oni", "Gar", "Pot", "Squ", "Let"],
    "2020-09-24": ["Let", "Bro", "Tom", "Oni", "Gar", "Cou", "Car"],
    "2020-09-25": [
        "Mus",
        "Let",
        "Bro",
        "Avo",
        "Pep",
        "Pot",
        "Pea",
        "Tom",
        "GrB",
        "Oni",
    ],
    "2020-09-26": ["Pot", "Tom", "Oni", "Bea", "Avo", "Car"],
    "2020-09-27": ["Pot", "Cou", "Pep", "Lee", "Car"],
    "2020-09-28": ["Pot", "Cou", "Pep", "Oni", "Lee", "Car"],
    "2020-09-29": ["Tom", "Oni", "Gar", "Oli", "Pot", "Car"],
    "2020-09-30": [
        "Tom",
        "Oni",
        "Gar",
        "Oli",
        "Pot",
        "Bea",
        "Car",
        "Let",
        "Avo",
    ],
    "2020-10-01": ["Let", "Avo", "Oni", "Gar"],
    "2020-10-02": ["Avo", "Let", "Car", "Oni", "Gar", "Oli"],
    "2020-10-03": ["Pot", "Gar", "Oni", "Squ", "Cel", "Mus"],
    "2020-10-04": ["Squ", "Car", "Oni", "Cab", "Pot", "Let", "Tom", "Oli"],
    "2020-10-05": [
        "Tom",
        "Gar",
        "Oni",
        "Oli",
        "Pep",
        "Let",
        "Mus",
        "Cel",
        "Lee",
        "Pot",
        "Car",
        "Cou",
        "SpO",
        "Cab",
    ],
    "2020-10-06": [
        "Avo",
        "Pot",
        "Squ",
        "Lee",
        "Car",
        "Let",
        "Oli",
        "Oni",
        "Mus",
        "Tom",
    ],
    "2020-10-07": ["Pot", "Car", "Squ", "Lee", "Oni", "Gin", "Gar", "Cel"],
    "2020-10-08": ["Oli", "Let", "Car", "Lee", "Pot"],
    "2020-10-09": ["Let", "Car", "Pot", "Lee", "Gar", "Cau"],
    "2020-10-10": ["Let", "Oli", "Avo", "Pot", "Gar", "Oni", "Squ"],
    "2020-10-11": [
        "Let",
        "Squ",
        "Avo",
        "Oni",
        "Car",
        "Pep",
        "Mus",
        "Bok",
        "Cou",
        "Gar",
        "BeS",
    ],
    "2020-10-12": [
        "Cau",
        "Car",
        "BeS",
        "Gar",
        "Pep",
        "Mus",
        "Bok",
        "Cou",
        "Oni",
        "Avo",
        "Let",
    ],
    "2020-10-13": ["Car", "Let", "Avo", "Oli", "BeS", "Pep", "Tom", "Mus"],
    "2020-10-14": ["Avo", "Let", "Oli", "Squ", "Pot", "BrS"],
    "2020-10-15": ["Avo", "Let", "Oni", "Squ", "Gar", "Tom", "Oli"],
    "2020-10-16": ["Avo", "Let", "Tom", "Pot", "Cou", "Oni"],
    "2020-10-17": ["Tom", "Car", "Let", "Oni", "Pep", "Oli", "Pot"],
    "2020-10-18": [
        "Tom",
        "Avo",
        "Oli",
        "Oni",
        "Pep",
        "Car",
        "Gar",
        "Cel",
        "Pot",
        "Lee",
        "SeW",
    ],
    "2020-10-19": ["Oni", "Car", "Gar", "Cel", "Pot", "Lee", "Cab"],
    "2020-10-20": ["Oni", "Gar", "Pot", "Car", "Cel", "Lee", "Cab", "Squ"],
    "2020-10-21": ["SpO", "Car", "SeW", "Pot", "Squ", "Cab"],
    "2020-10-22": ["Pot", "Car", "Cel", "Oni", "Gar", "Pep"],
    "2020-10-23": ["Oni", "Car", "Squ", "Gar", "Oli"],
    "2020-10-24": ["Squ", "Pea", "Oni", "Car", "Gar", "Mus"],
    "2020-10-25": ["Squ", "Oni", "Gar", "Par", "Swe", "Cha", "Mus", "Let"],
    "2020-10-26": [
        "Car",
        "Swe",
        "Par",
        "Gar",
        "Oni",
        "Squ",
        "Kal",
        "Let",
        "Oli",
        "SpO",
    ],
    "2020-10-27": ["Pep", "SpO", "Kal", "Oli", "Car", "Col", "Gar"],
    "2020-10-28": ["Car", "SpO", "Oni", "Pot"],
    "2020-10-29": ["Oni", "Pot", "Gar", "Tom", "Car", "Avo"],
    "2020-10-30": ["Car", "Cab", "Pot", "Tom", "Gar", "Oni", "Avo"],
    "2020-10-31": ["SpO", "Cau", "Squ", "Oni", "Gar", "Car", "Can", "Pot"],
    "2020-11-01": ["Oni", "Gar", "Squ", "Cau", "Pea", "Car", "Let", "Oli"],
    "2020-11-02": ["Let", "Squ", "Cab", "Car", "Pea", "Oli"],
    "2020-11-03": ["Let", "Squ", "Oni", "Gar", "Tom", "Car"],
    "2020-11-04": ["Cel", "Oni", "Gar", "Mus", "Tom", "Pea", "Squ"],
    "2020-11-05": ["SpO", "Car", "Oli", "Cel", "Oni", "Mus", "Pea", "Squ"],
    "2020-11-06": ["Car", "Oli", "Cab", "BeS", "Oni", "Gar", "Bro", "Squ"],
    "2020-11-07": ["Car", "Cab", "Gin", "Kal", "Oni", "Sea", "BeS"],
    "2020-11-08": [
        "Car",
        "Cab",
        "SpO",
        "Gar",
        "Oni",
        "Cou",
        "Kal",
        "Squ",
        "Lee",
        "Swe",
        "Cel",
        "Pot",
    ],
    "2020-11-09": [
        "Car",
        "Cab",
        "BeS",
        "Oli",
        "Kal",
        "SwP",
        "Oni",
        "Gar",
        "Lee",
        "Swe",
        "Cel",
        "Pot",
    ],
    "2020-11-10": [
        "Cel",
        "Gin",
        "Oni",
        "Cou",
        "Mus",
        "Gar",
        "Oli",
        "BrS",
        "Pot",
        "Car",
        "Avo",
    ],
    "2020-11-11": [
        "Cel",
        "Oni",
        "Gar",
        "Gin",
        "Mus",
        "Car",
        "Cau",
        "Let",
        "Oli",
        "Avo",
        "Pot",
        "Cuc",
    ],
    "2020-11-12": [
        "Cab",
        "Oni",
        "Par",
        "Let",
        "Car",
        "Oli",
        "GrB",
        "Avo",
        "Gin",
    ],
    "2020-11-13": [
        "Cab",
        "Car",
        "Par",
        "Let",
        "Oli",
        "Avo",
        "GrB",
        "Oni",
        "Lee",
        "Cel",
        "Mus",
    ],
    "2020-11-14": [
        "Cel",
        "Lee",
        "Mus",
        "Cab",
        "Car",
        "Avo",
        "Let",
        "Oli",
        "Pep",
        "Oni",
        "Gar",
        "Bea",
        "Pot",
    ],
    "2020-11-15": [
        "Car",
        "Cab",
        "Pot",
        "Bea",
        "Pep",
        "Oni",
        "Gar",
        "Avo",
        "Let",
        "Gin",
        "Oli",
    ],
    "2020-11-16": ["Squ", "Oni", "Car", "Let", "Avo"],
    "2020-11-17": [
        "Car",
        "Cab",
        "Gar",
        "Mus",
        "Cel",
        "Oni",
        "Oli",
        "Squ",
        "Par",
    ],
    "2020-11-18": ["Car", "Cab", "Squ", "Par", "Oni", "Gin"],
    "2020-11-19": ["Car", "Cab", "Avo", "Gar", "Oni", "Bea", "Oli", "Her"],
    "2020-11-20": [
        "Lee",
        "Cel",
        "Mus",
        "Bea",
        "Oni",
        "Cab",
        "Gar",
        "Par",
        "Squ",
        "Bee",
        "Cau",
        "Her",
    ],
    "2020-11-21": [
        "Her",
        "Par",
        "Squ",
        "Kal",
        "Avo",
        "Car",
        "Cel",
        "Oni",
        "Gar",
        "Cau",
        "Tom",
    ],
    "2020-11-22": [
        "Her",
        "Kal",
        "Tom",
        "Gar",
        "Oni",
        "Cel",
        "Avo",
        "Car",
        "Lee",
        "Par",
        "Pot",
        "Cau",
    ],
    "2020-11-23": [
        "Tom",
        "Oni",
        "Gar",
        "Car",
        "Cel",
        "Cau",
        "Pot",
        "Spi",
        "Mus",
    ],
    "2020-11-24": ["Her", "Oni", "Car", "Cau", "Avo", "Tom", "Let", "Oli"],
    "2020-11-25": [
        "SpO",
        "Cab",
        "Car",
        "Oni",
        "Squ",
        "Gar",
        "Let",
        "Oli",
        "Avo",
        "Tom",
        "Her",
    ],
    "2020-11-26": [
        "SpO",
        "Cab",
        "Tom",
        "Oni",
        "Gar",
        "Car",
        "Mus",
        "Lee",
        "Gin",
        "Pea",
    ],
    "2020-11-27": [
        "Oni",
        "Gin",
        "Pea",
        "Lee",
        "Mus",
        "Car",
        "Squ",
        "Bea",
        "Gar",
        "Avo",
        "Let",
        "Oli",
    ],
    "2020-11-28": [
        "Oni",
        "Par",
        "Squ",
        "Pot",
        "Cab",
        "Car",
        "Let",
        "Oli",
        "Avo",
        "Bea",
        "Gar",
    ],
    "2020-11-29": ["Oni", "Pot", "Squ", "Cab", "Avo", "Car"],
    "2020-11-30": ["Cab", "Squ", "Par", "Oni", "Gar", "Avo", "Car"],
    "2020-12-01": ["Car", "Pea", "Sea", "Oni", "Cab"],
    "2020-12-02": ["Let", "Oni", "Gar", "Cab", "Car", "Cel", "Mus"],
    "2020-12-03": [
        "Oni",
        "Gar",
        "Cel",
        "Car",
        "Mus",
        "Let",
        "Avo",
        "Oli",
        "Car",
        "Cab",
    ],
    "2020-12-04": ["Car", "Cel", "Mus", "Gar", "Avo", "SwP", "Kal"],
    "2020-12-05": [
        "Car",
        "Cab",
        "Gin",
        "Gar",
        "Cel",
        "Cou",
        "Oni",
        "SwP",
        "Let",
        "Oli",
    ],
    "2020-12-06": [
        "Sea",
        "Gin",
        "Gar",
        "Car",
        "Oni",
        "Par",
        "Swe",
        "Bro",
        "Pot",
        "Cou",
        "Cel",
        "Cab",
        "Lee",
    ],
    "2020-12-07": [
        "Oni",
        "Gar",
        "Mus",
        "Spi",
        "Cab",
        "Car",
        "Oli",
        "Pot",
        "Par",
        "Swe",
    ],
    "2020-12-08": ["Cab", "Car", "Mus", "Gar", "Oni", "Sea", "Cel", "Pea"],
    "2020-12-09": ["Car", "Cab", "Pot", "SwP", "Kal"],
    "2020-12-10": ["Let", "Car", "Avo"],
    "2020-12-11": ["Car", "Cab", "Avo", "Pot", "Let"],
    "2020-12-12": ["Gin", "Oni", "Gar", "Cau", "Pot", "Car", "Cou"],
    "2020-12-13": ["Car", "Cab", "Par", "Pot", "Cau", "Oni", "Gar", "Gin"],
    "2020-12-14": ["Car", "Cab", "Gin", "Cou", "Oni", "Gar", "Cel", "Mus"],
    "2020-12-15": ["Car", "Cab", "Oni", "Avo", "Oli", "Asp"],
    "2020-12-16": ["Avo", "Cab", "Oni", "Car", "Pot", "Cel", "Par"],
    "2020-12-17": ["Avo", "Oil", "Oni", "Car", "Pot", "Cel", "Par", "Cab"],
    "2020-12-18": ["Cab", "Car", "Oni", "Pot", "Par", "Cel", "Cau", "Pea"],
};
