type Account @collection(name: "accounts") {
  emailA: String! @unique
  emailB: String! @unique
  profile: Profile! @relation
}

type: Profile @collection(name: "profiles") {
  name: String!
  log: Log! @relation
  member: [Group!]! @relation
  owner: [Group!]! @relation
}

type Log @collection(name: "logs") {
  days: [Day!]!
}

type Day @embedded {
  date: String! @unique
  codes: [String!]!
}

type Group @collection(name: "groups") {
  name: String!
  intro: String!
  tags: [String!]!
  members: [Profile!]! @relation
  owners: [Profile!]! @relation
}

type Mutation {
  register(email: String!, password: String!): Account! @resolver
  login(email: String!, password: String!): String! @resolver
}
